services:
  sqlserver:
    build:
      context: ./docker/sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=temPass#
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=temPass#
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sqlserver_data: